import org.apache.spark.sql.Row

class DataPreprocessing {

  // Split the string based on the comma (`,`) delimiter
  //val resultArray: Array[String] = inputString.split(",")

  /*// Sample DataFrame
  val data_2 = Seq(
    Row("This is the first document.", 1),
    Row("This document is the second document.", 0),
    Row("And this is the third one.", 1),
    Row("Is this the first document? ", 1),
    Row("COVID-19 vaccines prove highly effective in preventing severe illness", 1),
    Row("Global economy shows signs of recovery after the pandemic", 1),
    Row("Scientists make progress in the development of a malaria vaccine", 1),
    Row("UN Climate Change Conference results in new commitments to reduce emissions", 1),
    Row("NASA's Ingenuity helicopter successfully completes multiple flights on Mars", 1),
    Row("Groundbreaking study identifies new treatment for Alzheimer's disease", 1),
    Row("International effort leads to the successful restoration of a coral reef", 1),
    Row("Renewable energy sources surpass coal in the United States for the first time", 1),
    Row("Researchers discover a new species of deep-sea marine life", 1),
    Row("Global initiative aims to plant one trillion trees to combat climate change", 1),
    Row("WHO announces the eradication of wild poliovirus in Africa", 1),
    Row("First-ever image of a black hole captured by the Event Horizon Telescope", 1),
    Row("SpaceX's Crew Dragon successfully docks with the International Space Station", 1),
    Row("Breakthrough in cancer research leads to promising new treatment options", 1),
    Row("World Health Organization approves a new malaria vaccine for use in children", 1),
    Row("NASA's Perseverance Rover collects first samples of Martian rock", 1),
    Row("Global efforts lead to a significant decline in new HIV infections", 1),
    Row("Advancements in gene therapy show promise in treating genetic disorders", 1),
    Row("International collaboration results in the successful sequencing of the human genome", 1),
    Row("UNESCO designates new World Heritage Sites to protect cultural and natural treasures", 1),
    Row("Breakthrough in fusion energy research brings us closer to clean and abundant energy", 1),
    Row("Scientists develop a promising new treatment for drug-resistant tuberculosis", 1),
    Row("World leaders commit to ambitious goals to protect biodiversity", 1),
    Row("Successful trial of a universal flu vaccine raises hopes for better influenza prevention", 1),
    Row("Renewable energy capacity surpasses coal and gas for the first time globally", 1),
    Row("International Space Station celebrates 20 years of continuous human presence", 1),
    Row("Global initiative aims to eliminate single-use plastics by 2030", 1),
    Row("Researchers make significant progress in the quest for a viable HIV vaccine", 1),
    Row("Advancements in CRISPR technology open new possibilities for gene editing", 1),
    Row("NASA's Juno spacecraft provides unprecedented insights into Jupiter's atmosphere", 1),
    Row("Breakthrough in Alzheimer's research identifies a blood test for early detection", 1),
    Row("International collaboration leads to the discovery of a potential treatment for Ebola", 1),
    Row("Renewable energy outpaces fossil fuels in the European electricity mix", 1),
    Row("Scientists achieve a major milestone in the development of a COVID-19 antiviral pill", 1),
    Row("Global initiative aims to protect 30% of the world's oceans by 2030", 1),
    Row("NASA's Artemis program aims to return humans to the Moon by 2024", 1),
    Row("Breakthrough in quantum computing brings us closer to practical applications", 1),
    Row("International Space Station completes 100,000 orbits around Earth", 1),
    Row("Advancements in solar technology lead to more efficient and affordable panels", 1),
    Row("Global efforts to combat deforestation focus on reforestation initiatives", 1),
    Row("Researchers achieve a major milestone in the development of a COVID-19 vaccine for children", 1),
    Row("UNESCO adds the Great Barrier Reef to the list of World Heritage Sites in danger", 1),
    Row("Scientists successfully use CRISPR gene editing to treat a genetic disorder in vivo", 1),
    Row("Global initiative aims to provide COVID-19 vaccines to low-income countries", 1),
    Row("NASA's James Webb Space Telescope set to launch, promising new discoveries", 1),
    Row("Breakthrough in stem cell research offers potential for regenerative medicine", 1),
    Row("International collaboration results in the successful eradication of rinderpest", 1),
    Row("Renewable energy capacity in the United States surpasses coal for the first time", 1),
    Row("Scientists discover a new exoplanet with potential for signs of life", 1),
    Row("Global effort leads to the successful conservation of endangered species", 1),
    Row("NASA's InSight lander provides valuable insights into Mars' seismic activity", 1),
    Row("Breakthrough in AI research enables more accurate weather predictions", 1),
    Row("International collaboration results in the successful development of a malaria vaccine", 1),
    Row("Advancements in 3D printing technology revolutionize healthcare applications", 1),
    Row("Global initiative aims to eliminate river blindness in affected regions", 1),
    Row("Researchers make progress in the development of a universal cancer vaccine", 1),
    Row("UNESCO recognizes traditional Japanese washoku cuisine as intangible cultural heritage", 1),
    Row("Renewable energy surpasses fossil fuels as the largest source of new power capacity", 1),
    Row("Scientists discover a new species of dinosaur in Argentina", 1),
    Row("Breakthrough in the development of a malaria vaccine for pregnant women", 1),
    Row("NASA's Juno spacecraft uncovers new mysteries about Jupiter's magnetic field", 1),
    Row("Global efforts lead to the successful conservation of giant pandas", 1),
    Row("Advancements in fusion energy research bring us closer to sustainable power", 1),
    Row("International collaboration results in the successful sequencing of the wheat genome", 1),
    Row("Renewable energy capacity in China surpasses the rest of the world combined", 1),
    Row("Researchers achieve a major breakthrough in the development of a universal flu vaccine", 1),
    Row("Breakthrough in artificial photosynthesis technology for sustainable fuel production", 1),
    Row("NASA's Parker Solar Probe provides unprecedented close-up views of the Sun", 1),
    Row("Global initiative aims to eliminate blinding trachoma in affected regions", 1),
    Row("Scientists make progress in the development of a Zika virus vaccine", 1),
    Row("International collaboration results in the successful restoration of a mangrove forest", 1),
    Row("Advancements in quantum computing open new possibilities for scientific research", 1),
    Row("Renewable energy capacity in India sees significant growth", 1),
    Row("NASA's New Horizons spacecraft provides detailed images of Pluto's surface", 1),
    Row("Breakthrough in CRISPR technology allows for precise gene editing in plants", 1),
    Row("Global efforts lead to the successful conservation of the Amur leopard", 1),
    Row("Researchers achieve a major milestone in the development of a malaria vaccine for infants", 1),
    Row("UNESCO designates ancient Babylon as a World Heritage Site", 1),
    Row("Renewable energy surpasses coal as the largest source of power in the European Union", 1),
    Row("International collaboration results in the successful elimination of Guinea worm disease", 1),
    Row("Breakthrough in AI research leads to improved diagnosis of rare genetic disorders", 1),
    Row("NASA's TESS mission discovers a new exoplanet with potential for habitability", 1),
    Row("Advancements in gene therapy show promise in treating Duchenne muscular dystrophy", 1),
    Row("Global initiative aims to protect the world's remaining wilderness areas", 1),
    Row("Researchers make progress in the development of a malaria vaccine for adults", 1),
    Row("Renewable energy capacity in Australia reaches a new record", 1),
    Row("NASA's OSIRIS-REx spacecraft successfully collects samples from asteroid Bennu", 1),
    Row("Breakthrough in the development of a universal flu vaccine shows promising results", 1),
    Row("International collaboration results in the successful conservation of the vaquita", 1),
    Row("Advancements in CRISPR technology allow for precise gene editing in animals", 1),
    Row("UNESCO designates the Okavango Delta as a World Heritage Site", 1),
    Row("Renewable energy capacity in Germany surpasses coal for the first time", 1),
    Row("NASA's Juno spacecraft provides stunning images of Jupiter's polar regions", 1),
    Row("Breakthrough in the development of a COVID-19 treatment reduces severity of illness", 1),
    Row("Global initiative aims to eliminate mother-to-child transmission of HIV", 1),
    Row("Researchers make progress in the development of a universal cancer vaccine", 1),
    Row("Advancements in fusion energy research bring us closer to sustainable power", 1),
    Row("Renewable energy capacity in India sees significant growth", 1),
    Row("NASA's New Horizons spacecraft provides detailed images of Pluto's surface", 1),
    Row("Breakthrough in CRISPR technology allows for precise gene editing in plants", 1),
    Row("Scientists discover a parallel universe where gravity pushes instead of pulls", 0),
    Row("New law requires citizens to wear socks on their hands in public", 0),
    Row("Incredible breakthrough: Plants develop the ability to communicate with each other", 0),
    Row("Government introduces mandatory daily dance breaks for all citizens", 0),
    Row("Study finds that laughter can be used as a renewable energy source", 0),
    Row("Penguins start their own rock band and top the charts", 0),
    Row("Researchers create a device that turns dreams into reality", 0),
    Row("Aliens demand to be included in Earth's next census", 0),
    Row("New scientific experiment turns tomatoes into strawberries", 0),
    Row("International hot dog shortage declared; world leaders convene emergency summit", 0),
    Row("Astronauts host a space-themed cooking show from the International Space Station", 0),
    Row("Invention allows humans to breathe underwater; scuba diving industry in crisis", 0),
    Row("Government to replace all road signs with emojis for better communication", 0),
    Row("Scientists develop a potion that grants invisibility for 24 hours", 0),
    Row("World record set for the largest synchronized dance by robots", 0),
    Row("New law requires pets to obtain a driver's license for traveling in cars", 0),
    Row("Researchers create a language translation device for babies", 0),
    Row("Robots form a union and go on strike for better working conditions", 0),
    Row("International competition held to find the world's best cloud shapers", 0),
    Row("Government to launch a mission to bring back dinosaurs from extinction", 0),
    Row("Study suggests that talking to plants improves their growth", 0),
    Row("Chocolate declared the official currency in a small island nation", 0),
    Row("Scientists develop a pill that allows humans to hibernate for months", 0),
    Row("Penguins organize a global conference on ice preservation", 0),
    Row("New law mandates wearing pajamas to work for increased productivity", 0),
    Row("Space agency plans to build a space hotel on the moon by 2030", 0),
    Row("Astronauts discover a giant alien snowman on a distant planet", 0),
    Row("Government to implement a mandatory daily hour of bubble-wrap popping", 0),
    Row("Researchers create a device that translates baby cries into words", 0),
    Row("International competition for the best underwater sculpture garden", 0),
    Row("Government to build a giant trampoline to ease commuter traffic", 0),
    Row("Scientists create a pill that makes people immune to bad hair days", 0),
    Row("Robots form a jazz band and release a chart-topping album", 0),
    Row("New law requires citizens to celebrate their half-birthdays with a parade", 0),
    Row("Researchers develop a machine that turns thoughts into text", 0),
    Row("Government introduces a tax break for citizens who own talking pets", 0),
    Row("Astronauts organize a marathon on the surface of Mars", 0),
    Row("International competition for the best treehouse design", 0),
    Row("Scientists create a device that allows people to taste colors", 0),
    Row("Penguins start a social media platform exclusively for birds", 0),
    Row("New law requires everyone to wear hats made of recycled materials", 0),
    Row("Government to launch a mission to explore the mysteries of the Bermuda Triangle", 0),
    Row("Researchers develop a device that allows humans to understand animal languages", 0),
    Row("Scientists discover a species of fish that can play musical instruments", 0),
    Row("Astronauts organize a space-themed fashion show on the International Space Station", 0),
    Row("International competition for the best sandcastle construction", 0),
    Row("Government to implement a nationwide pillow fight day", 0),
    Row("New law requires citizens to carry a rubber chicken for good luck", 0),
    Row("Researchers develop a device that allows plants to send text messages", 0),
    Row("Penguins create a documentary on the art of belly sliding", 0),
    Row("Scientists create a pill that makes people immune to boredom", 0),
    Row("Astronauts organize a zero-gravity dance competition", 0),
    Row("Government plans to build a roller coaster around the Eiffel Tower", 0),
    Row("International competition for the best cloud-gazing experience", 0),
    Row("New law requires citizens to celebrate their pets' birthdays with a national holiday", 0),
    Row("Researchers develop a device that allows humans to fly like birds", 0),
    Row("Scientists discover a planet where chocolate grows on trees", 0),
    Row("Astronauts organize a space-themed cooking competition on Mars", 0),
    Row("Government to launch a mission to search for the mythical city of Atlantis", 0),
    Row("International competition for the best invention using recycled materials", 0),
    Row("New law requires citizens to take a daily dose of laughter for improved well-being", 0),
    Row("Researchers develop a device that allows humans to communicate with dolphins", 0),
    Row("Penguins start a podcast on the challenges of living in Antarctica", 0),
    Row("Scientists create a pill that allows people to understand the language of insects", 0),
    Row("Astronauts organize a space-themed art exhibition on the moon", 0),
    Row("Government plans to build an underwater city for marine life", 0),
    Row("International competition for the best underwater dance performance", 0),
    Row("New law requires citizens to take a daily break for cloud-watching", 0),
    Row("Researchers develop a device that allows humans to experience dreams of their choice", 0),
    Row("Scientists create a pill that makes people immune to Monday blues", 0),
    Row("Astronauts organize a space-themed music festival in orbit", 0),
    Row("Government to launch a mission to search for extraterrestrial intelligence", 0),
    Row("International competition for the best tree-climbing technique", 0),
    Row("New law requires citizens to celebrate the first day of spring with a nationwide picnic", 0),
    Row("Researchers develop a device that allows humans to understand the language of birds", 0),
    Row("Penguins organize a synchronized swimming competition in the Antarctic Ocean", 0),
    Row("Scientists create a pill that allows people to understand the language of whales", 0),
    Row("Astronauts organize a space-themed dance party on the International Space Station", 0),
    Row("Government plans to build a giant maze in the middle of a desert", 0),
    Row("International competition for the best sand sculpture of a mythical creature", 0),
    Row("New law requires citizens to participate in a weekly dance-off for community bonding", 0),
    Row("Researchers develop a device that allows humans to communicate with trees", 0),
    Row("Scientists create a pill that makes people immune to bad weather", 0),
    Row("Astronauts organize a space-themed film festival on Mars", 0),
    Row("Government to launch a mission to explore the mysteries of the deep sea", 0),
    Row("International competition for the best underwater treasure hunt", 0),
    Row("New law requires citizens to celebrate the first snowfall with a snowball fight", 0),
    Row("Researchers develop a device that allows humans to understand the language of elephants", 0),
    Row("Penguins start a campaign to raise awareness about climate change in Antarctica", 0),
    Row("Scientists create a pill that allows people to understand the language of bees", 0),
    Row("Astronauts organize a space-themed fashion week on the International Space Station", 0),
    Row("Government plans to build a giant umbrella to shade a city from the sun", 0),
    Row("International competition for the best sandcastle on a desert island", 0),
    Row("New law requires citizens to celebrate the first day of summer with a water balloon fight", 0),
    Row("Researchers develop a device that allows humans to understand the language of dolphins", 0),
    Row("Scientists create a pill that makes people immune to traffic jams", 0),
    Row("Astronauts organize a space-themed talent show on the moon", 0),
    Row("Government to launch a mission to create a sustainable floating city", 0),
    Row("International competition for the best invention using recycled ocean plastic", 0),
    Row("New law requires citizens to celebrate the first day of autumn with a pumpkin carving contest", 0)
  )
  // Define the schema for the DataFrame
  val schema_2 = StructType(Seq(
    StructField("title", StringType, true),
    StructField("label", IntegerType, true)
  ))
  finalDataset = spark.createDataFrame(spark.sparkContext.parallelize(data_2), schema_2)*/
  
}
